### PR TITLE
windows path

### PR DESCRIPTION
**Pull request by HalfLegend**
- handle windows paths
- Update RType.scala
- 1. Update scala version to 3.1.0 2. Update file path resolving

### CODE REVIEW

**Comment by pjfanning** [comment]
why do you need to change the scala version? scala 3.1.0 built jars will not work for scala 3.0.x runtime - but scala 3.0 built jars work on scala 3.1 runtime - so building with scala 3.0 maintains maximum compatibility

**Comment by HalfLegend** [comment]
> 
Because I find you upgraded the version of sbt
I don't know the impact of changing the scala version. 
In my opinion unlike scala 2, changing a minor version of scala 3 will cause less impact.
Ok I will keep the scala version

**Comment by pjfanning** [comment]
@HalfLegend your PathResolver code relies on new Java methods that mean you break support for Java 8 users.

[error] -- [E008] Not Found Error: /home/runner/work/scala3-reflection/scala3-reflection/src/main/scala/co.blocke.scala_reflection/impl/PathResolver.scala:10:23 
[error] 10 |      .map(src => Path.of(src))
[error]    |                  ^^^^^^^
[error]    |                  value of is not a member of object java.nio.file.Path
[error] -- [E008] Not Found Error: /home/runner/work/scala3-reflection/scala3-reflection/src/main/scala/co.blocke.scala_reflection/impl/PathResolver.scala:11:24 
[error] 11 |      .map(path => path.resolve(clazz.getName.replace(".", File.separator) + ".tasty").normalize())
[error]    |                   ^^^^^^^^^^^^
[error]    |                   value resolve is not a member of Nothing
[error] two errors found
[error] two errors found

**Comment by HalfLegend** [comment]
> @HalfLegend your PathResolver code relies on new Java methods that mean you break support for Java 8 users.
> 
> [error] -- [E008] Not Found Error: /home/runner/work/scala3-reflection/scala3-reflection/src/main/scala/co.blocke.scala_reflection/impl/PathResolver.scala:10:23 [error] 10 | .map(src => Path.of(src)) [error] | ^^^^^^^ [error] | value of is not a member of object java.nio.file.Path [error] -- [E008] Not Found Error: /home/runner/work/scala3-reflection/scala3-reflection/src/main/scala/co.blocke.scala_reflection/impl/PathResolver.scala:11:24 [error] 11 | .map(path => path.resolve(clazz.getName.replace(".", File.separator) + ".tasty").normalize()) [error] | ^^^^^^^^^^^^ [error] | value resolve is not a member of Nothing [error] two errors found [error] two errors found

Yes .... It should be Paths.get

**Comment by pjfanning** [comment]
thanks @HalfLegend - I tested this using a windows build agent on github actions and it works well

**Comment by HalfLegend** [comment]
@pjfanning @gzoller 
Could you please aprove this PR and publish a new version to maven central? I need this fix eagerly
Thanks very much

**Comment by gzoller** [comment]
Ok, 1.1.3 is released.  Give it a bit for the interwebs to distribute it around to the usual places.
